'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {

        await queryInterface.bulkInsert('Series', [{
                id_serie: 1,
                title: 'Dragon Ball Z',
                date: 1989,
                episode_7_days: false,
                episodes: 291,
                seassons: 9,
                poster: "	https://www.themoviedb.org/t/p/w1280/7yMFXciYDcMle8BjbCsrZ8aqHtw.jpg",
                rank: 1,
                cinema: true,
                theater: false,
                id_article: 2
            },
            {
                id_serie: 2,
                title: 'Dragon Ball',
                date: 1986,
                episode_7_days: false,
                episodes: 153,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w1280/9kK5dRLHbw4QOoFcIAKK2gnOVmx.jpg",
                rank: 2,
                cinema: true,
                theater: false,
                id_article: 4
            },
            {
                id_serie: 3,
                title: 'Castle',
                date: 2009,
                episode_7_days: false,
                episodes: 173,
                seassons: 8,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gkXKYjCjjEcRhYPMBLrB4SPPp91.jpg",
                rank: 3,
                cinema: false,
                theater: false,
                id_article: 6
            },
            {
                id_serie: 4,
                title: 'Mentes Criminales',
                date: 2005,
                episode_7_days: true,
                episodes: 334,
                seassons: 16,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3UyUgPfcs7ByA9hxbhWSW98xdpg.jpg",
                rank: 4,
                cinema: false,
                theater: false,
                id_article: 8
            }, {
                id_serie: 5,
                title: 'Supergol',
                date: 1986,
                episode_7_days: false,
                episodes: 26,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/n4KLsqSXBLsR72gklIVDem1jvpD.jpg",
                rank: 5,
                cinema: false,
                theater: false,
                id_article: 10
            },
            {
                id_serie: 6,
                title: 'Los Caballeros del Zodiaco',
                date: 1986,
                episode_7_days: false,
                episodes: 114,
                seassons: 1,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rYp2lHcM5rsdEdzuYA56lk7xBDr.jpg",
                rank: 6,
                cinema: false,
                theater: false,
                id_article: 12
            },
            {
                id_serie: 7,
                title: 'La casa de papel',
                date: 2017,
                episode_7_days: false,
                episodes: 41,
                seassons: 3,
                poster: "https://www.themoviedb.org/t/p/w1280/zd8mxIfGY8SlupYd9XvK3qJL91B.jpg",
                rank: 7,
                cinema: true,
                theater: false,
                id_article: 14
            },
            {
                id_serie: 8,
                title: 'El juego del calamar',
                date: 2021,
                episode_7_days: false,
                episodes: 9,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yvW9VuHiwfAaTNYjALROI8evNIT.jpg",
                rank: 8,
                cinema: false,
                theater: false,
                id_article: 16
            },
            {
                id_serie: 9,
                title: 'La vuelta al mundo de Willy Fog',
                date: 1983,
                episode_7_days: false,
                episodes: 26,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/w8rCmXOatxeKtgSw9tEUCxuA9Rd.jpg",
                rank: 9,
                cinema: false,
                theater: true,
                id_article: 18
            },
            {
                id_serie: 10,
                title: 'Dartacan y los tres mosqueperros',
                date: 1981,
                episode_7_days: false,
                episodes: 26,
                seassons: 1,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vEQa7aX3rHWbDbBtWfsEJ8Q5ydx.jpg",
                rank: 10,
                cinema: false,
                theater: false,
                id_article: 20
            },
            {
                id_serie: 11,
                title: 'Mazinger Z',
                date: 1972,
                episode_7_days: false,
                episodes: 92,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w1280/kShVS4uxArtR3WMvvweVD7lPWeX.jpg",
                rank: 11,
                cinema: false,
                theater: false,
                id_article: 22
            },
            {
                id_serie: 12,
                title: 'Power Rangers',
                date: 1993,
                episode_7_days: true,
                episodes: 963,
                seassons: 30,
                poster: "https://www.themoviedb.org/t/p/w1280/8lnX8RWeGBdEQPOvf2IKoRtKfZO.jpg",
                rank: 12,
                cinema: true,
                theater: false,
                id_article: 24
            },
            {
                id_serie: 13,
                title: 'Los hombres de Paco',
                date: 2005,
                episode_7_days: false,
                episodes: 133,
                seassons: 10,
                poster: "https://www.themoviedb.org/t/p/w1280/uh2W9FyVQ65FYFQwX4C9FRjW7DY.jpg",
                rank: 13,
                cinema: false,
                theater: false,
                id_article: 26
            },
            {
                id_serie: 14,
                title: 'Campeones: Oliver y Benji',
                date: 1983,
                episode_7_days: false,
                episodes: 128,
                seassons: 5,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ylTQ8kWL2Ln5aS4W7r8ajFB5kcp.jpg",
                rank: 14,
                cinema: true,
                theater: false,
                id_article: 28
            },
            {
                id_serie: 15,
                title: 'Chicho Terremoto',
                date: 1981,
                episode_7_days: false,
                episodes: 65,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rvfgoeTvdJgsx3iYNXcNRAoCgbQ.jpg",
                rank: 15,
                cinema: false,
                theater: false,
                id_article: 30
            },
            {
                id_serie: 16,
                title: 'Teen Wolf',
                date: 1986,
                episode_7_days: false,
                episodes: 21,
                seassons: 2,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iFPVcdkYhx34E1JPOkCPknX1dt5.jpg",
                rank: 16,
                cinema: true,
                theater: false,
                id_article: 32
            },
            {
                id_serie: 17,
                title: 'Musculman',
                date: 1983,
                episode_7_days: false,
                episodes: 183,
                seassons: 2,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8VbmANlFnpgGGljbwFjvKIJJdCW.jpg",
                rank: 17,
                cinema: false,
                theater: false,
                id_article: 34
            },
            {
                id_serie: 18,
                title: 'Las Tortugas Ninja',
                date: 1987,
                episode_7_days: false,
                episodes: 193,
                seassons: 10,
                poster: "https://www.themoviedb.org/t/p/w1280/9vpWpUNKDbC41dRrsQziKREqp29.jpg",
                rank: 18,
                cinema: true,
                theater: false,
                id_article: 36
            },
            {
                id_serie: 19,
                title: 'He-man y los Masters del Universo',
                date: 1983,
                episode_7_days: false,
                episodes: 130,
                seassons: 2,
                poster: "https://www.themoviedb.org/t/p/w1280/g2thtQ6q0A9zVT8waPaECNO6XuD.jpg",
                rank: 19,
                cinema: true,
                theater: false,
                id_article: 38
            },
            {
                id_serie: 20,
                title: 'Los Trotamúsicos',
                date: 1989,
                episode_7_days: false,
                episodes: 26,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w1280/ogorqSGbfxB6Zm1k0k8dIm1BTmg.jpg",
                rank: 20,
                cinema: false,
                theater: true,
                id_article: 40
            },
            {
                id_serie: 21,
                title: 'The crwon',
                date: 2016,
                episode_7_days: true,
                episodes: 50,
                seassons: 5,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4a7HOUtb6sBpqmuByTxenRxlqds.jpg",
                rank: 21,
                cinema: false,
                theater: false,
                id_article: 42
            },
            {
                id_serie: 22,
                title: 'Juego de tronos',
                date: 2011,
                episode_7_days: false,
                episodes: 73,
                seassons: 8,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/z9gCSwIObDOD2BEtmUwfasar3xs.jpg",
                rank: 22,
                cinema: false,
                theater: false,
                id_article: 44
            },
            {
                id_serie: 23,
                title: 'La casa del Dragon',
                date: 2022,
                episode_7_days: true,
                episodes: 10,
                seassons: 1,
                poster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xiB0hsxMpgxpJehYxUDhiUkg2w.jpg",
                rank: 23,
                cinema: false,
                theater: false,
                id_article: 46
            },
            {
                id_serie: 24,
                title: 'El Señor de los Anillos: Los anillos de poder',
                date: 2022,
                episode_7_days: true,
                episodes: 8,
                seassons: 1,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/suvlZfDAoq5vfVUrfb468KJhFlL.jpg",
                rank: 24,
                cinema: true,
                theater: false,
                id_article: 48
            },
            {
                id_serie: 25,
                title: 'Dahmer-Monstruo: La historia de Jeffrey Dahmer',
                date: 2022,
                episode_7_days: true,
                episodes: 10,
                seassons: 1,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vlUMBgKO1HOwPMJwHnHzr99BHwN.jpg",
                rank: 25,
                cinema: false,
                theater: false,
                id_article: 50
            },
            {
                id_serie: 26,
                title: 'Cueéntame cómo pasó',
                date: 2001,
                episode_7_days: true,
                episodes: 409,
                seassons: 22,
                poster: "",
                rank: 26,
                cinema: true,
                theater: true,
                id_article: 52
            },
            {
                id_serie: 27,
                title: 'La que se avecina',
                date: 2007,
                episode_7_days: true,
                episodes: 178,
                seassons: 13,
                poster: "	https://www.themoviedb.org/t/p/w600_and_h900_bestv2/76GUieAvgHwH07Yd7kR86iay3dx.jpg",
                rank: 27,
                cinema: true,
                theater: false,
                id_article: 54
            },
            {
                id_serie: 28,
                title: '911',
                date: 2018,
                episode_7_days: true,
                episodes: 88,
                seassons: 6,
                poster: "https://www.themoviedb.org/t/p/w1280/jvStfYRsDrcVymTEgRbyHqpBXwz.jpg",
                rank: 28,
                cinema: true,
                theater: true,
                id_article: 56
            },

        ], {});

    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Series', null, {});

    }
};